language: go
go:
 - 1.4
install:
 - true
before_script:
 - go get golang.org/x/tools/cmd/vet
 - go get github.com/kr/godep
script:
 - export PATH=$PATH:$HOME/gopath/bin
 - ./hooks/check_boilerplate.sh
 - gofmt -l `find . -type f -name "*.go" | grep -v Godeps`
 - go vet github.com/skytap/heapster/...
 - godep go build -a github.com/skytap/heapster/...
 - godep go test -a -test.short ./... 
